# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "dev-proximity-terraform"
    dynamodb_table = "dev-proximity-terraform-lock"
    encrypt        = true
    key            = "dev/us-east-1/s3/proximity/terraform.tfstate"
    region         = "us-east-1"
  }
}
